---
name: "Sanity Check"

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Checkout"
        uses: actions/checkout@v4
      - 
        name: Restore cached Orbis SDK
        id: cache-orbis
        uses: actions/cache/restore@v3
        with:
          path: OpenOrbis
          key: orbis
      -
        name: "Setup Environment"
        run: |
          sudo apt-get update
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
      - 
        name: Download Orbis SDK
        if: ${{ !steps.cache-orbis.outputs.cache-hit }}
        run: |
          wget https://github.com/OpenOrbis/OpenOrbis-PS4-Toolchain/releases/download/v0.5.2/v0.5.2.tar.gz
          tar -xf v0.5.2.tar.gz
          rm v0.5.2.tar.g
      - 
        name: Cache Orbis SDK
        if: ${{ !steps.cache-orbis.outputs.cache-hit }}
        uses: actions/cache/save@v3
        with:
          path: OpenOrbis
          key: orbis
      -
        name: "Build Payload"
        run: |
          export OO_PS4_TOOLCHAIN=${{ github.workspace }}/OpenOrbis/PS4Toolchain/
          make
      -
        name: "Upload Binary Artifact"
        uses: actions/upload-artifact@v4
        with:
          path: ./*.pkg
          if-no-files-found: error
