---
name: "Sanity Check"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Checkout"
        uses: actions/checkout@v4
      -
        name: "Setup Environment"
        run: |
          git clone --depth 1 --branch v0.5.2 https://github.com/OpenOrbis/OpenOrbis-PS4-Toolchain /opt/openorbis-0.5.2
          sudo apt-get update
          sudo apt-get install -y clang-10 lldb-10 lld-10
      -
        name: "Build Payload"
        run: |
          export OO_PS4_TOOLCHAIN=/opt/openorbis-0.5.2
          make
      -
        name: "Upload Binary Artifact"
        uses: actions/upload-artifact@v4
        with:
          path: ./*.pkg
          if-no-files-found: error
